[project]
name = "rag-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "chromadb>=1.5.9",
    "click>=8.4.2",
    "fastapi[standard]>=0.141.1",
    "httpx2>=2.10.0",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-ollama>=1.1.0",
    "pdfplumber>=0.11.10",
    "pypdf>=6.16.1",
    "ragas==0.4.3",
    "tiktoken>=0.14.0",
]

[dependency-groups]
dev = [
    "httpx2[cli]>=2.10.0",
]
